TARGET_NAMES = MPGCombo1 MPGCombo2 MPGCombo3 MPGCombo4 MPGCombo5 MPGCombo6 MPGCombo7 MPGCombo8 MPGCombo9 MPGCombo10 MPGCombo11 MPGCombo12 MPGCombo13 MPGCombo14 MPGCombo15 MPGCombo16 MPGCombo17 MPGCombo18 MPGCombo19 MPGCombo23 MPGCombo24 MPGVBNSO MPGPSX1200Test

MPGCombo1.FLAGS = -DENABLE_REFLEX_PSX -DNEGCON_FORCE_MODE=1 -DNEGCON_SUPPORT -DENABLE_PSX_GENERAL_OLED -DENABLE_REFLEX_N64 -DENABLE_N64_ANALOG_MAX=85 -DENABLE_REFLEX_GAMECUBE
MPGCombo2.FLAGS = -DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY -DENABLE_REFLEX_SMS -DENABLE_REFLEX_JPC -DENABLE_REFLEX_NEOGEO -DENABLE_REFLEX_N64 -DENABLE_N64_ANALOG_MAX=85 -DENABLE_REFLEX_GAMECUBE
MPGCombo3.FLAGS = -DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY -DENABLE_REFLEX_PSX -DNEGCON_FORCE_MODE=1 -DNEGCON_SUPPORT -DENABLE_PSX_GENERAL_OLED -DENABLE_REFLEX_N64 -DENABLE_N64_ANALOG_MAX=85 
MPGCombo4.FLAGS = -DENABLE_REFLEX_SNES -DENABLE_REFLEX_NEOGEO -DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED -DENABLE_REFLEX_N64 -DENABLE_N64_ANALOG_MAX=85 
MPGCombo5.FLAGS = -DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY -DENABLE_REFLEX_PCE -DENABLE_REFLEX_NEOGEO -DENABLE_REFLEX_N64 -DENABLE_N64_ANALOG_MAX=85 -DENABLE_REFLEX_GAMECUBE
MPGCombo6.FLAGS = -DENABLE_REFLEX_SNES -DENABLE_REFLEX_PCE -DENABLE_REFLEX_NEOGEO -DENABLE_REFLEX_JAGUAR -DENABLE_REFLEX_SMS
MPGCombo7.FLAGS = -DENABLE_REFLEX_SATURN -DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED -DENABLE_REFLEX_NEOGEO -DENABLE_REFLEX_SMS
MPGCombo8.FLAGS = -DENABLE_REFLEX_SATURN -DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY -DENABLE_REFLEX_PCE -DENABLE_REFLEX_NEOGEO
MPGCombo9.FLAGS = -DENABLE_REFLEX_SATURN -DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY -DENABLE_REFLEX_N64 -DENABLE_N64_ANALOG_MAX=85 
MPGCombo10.FLAGS = -DENABLE_REFLEX_SATURN -DENABLE_REFLEX_NEOGEO -DENABLE_REFLEX_N64 -DENABLE_N64_ANALOG_MAX=80 -DENABLE_REFLEX_GAMECUBE
MPGCombo11.FLAGS = -DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED -DENABLE_REFLEX_3DO -DENABLE_REFLEX_WII
MPGCombo12.FLAGS = -DENABLE_REFLEX_SNES -DENABLE_REFLEX_SATURN -DENABLE_REFLEX_NEOGEO -DENABLE_REFLEX_GAMECUBE
MPGCombo13.FLAGS = -DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY -DENABLE_REFLEX_PSX -DNEGCON_FORCE_MODE=1 -DNEGCON_SUPPORT -DENABLE_PSX_GENERAL_OLED -DENABLE_REFLEX_GAMECUBE
# #85: Nintendo-heavy combo (NES/SNES/VB, N64, Wii)
# NOTE: Adding GameCube to this set exceeds MPG flash on CI toolchains.
MPGCombo14.FLAGS = -DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY -DENABLE_REFLEX_N64 -DENABLE_N64_ANALOG_MAX=80 -DENABLE_REFLEX_WII
# #83: Closest fit for SNES/NES + GEN/SAT + N64 + PCE
# NOTE: Including N64 with this set exceeds MPG flash on CI toolchains.
MPGCombo15.FLAGS = -DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY -DENABLE_REFLEX_SATURN -DENABLE_REFLEX_PCE
# #82: Wii + GEN/SAT
MPGCombo16.FLAGS = -DENABLE_REFLEX_SATURN -DENABLE_REFLEX_WII
# Nintendo without Wii (SNES/VB + N64 + GC)
MPGCombo17.FLAGS = -DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY -DENABLE_REFLEX_N64 -DENABLE_N64_ANALOG_MAX=80 -DENABLE_REFLEX_GAMECUBE
# Nintendo without N64 (SNES/VB + GC + Wii)
MPGCombo18.FLAGS = -DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY -DENABLE_REFLEX_GAMECUBE -DENABLE_REFLEX_WII
# Nintendo without SNES (N64 + GC + Wii)
MPGCombo19.FLAGS = -DENABLE_REFLEX_N64 -DENABLE_N64_ANALOG_MAX=80 -DENABLE_REFLEX_GAMECUBE -DENABLE_REFLEX_WII
# GEN/SAT + N64 + Wii
MPGCombo20.FLAGS = -DENABLE_REFLEX_SATURN -DENABLE_REFLEX_N64 -DENABLE_N64_ANALOG_MAX=80 -DENABLE_REFLEX_WII
# GEN/SAT + PCE + Wii
MPGCombo21.FLAGS = -DENABLE_REFLEX_SATURN -DENABLE_REFLEX_PCE -DENABLE_REFLEX_WII
# SNES/VB + GEN/SAT + Wii
MPGCombo22.FLAGS = -DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY -DENABLE_REFLEX_SATURN -DENABLE_REFLEX_WII
# SNES/VB + N64 + PCE
MPGCombo23.FLAGS = -DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY -DENABLE_REFLEX_N64 -DENABLE_N64_ANALOG_MAX=80 -DENABLE_REFLEX_PCE
# SNES/VB + GEN/SAT + N64
MPGCombo24.FLAGS = -DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY -DENABLE_REFLEX_SATURN -DENABLE_REFLEX_N64 -DENABLE_N64_ANALOG_MAX=80
MPGVBNSO.FLAGS = -DENABLE_REFLEX_SNES -DSNES_ENABLE_VBOY -DSNES_VBOY_RIGHT_DPAD_TO_RSTICK
MPGPSX1200Test.FLAGS = -DENABLE_REFLEX_PSX -DENABLE_PSX_GENERAL_OLED -DPSX_1200_TEST

PRJ_DIR = ReflexMPG
BUILD_DIR = build
TARGET_DIR = firmware

SRC = $(wildcard $(PRJ_DIR)/*.h $(PRJ_DIR)/*.c $(PRJ_DIR)/*.ino)
ARDUINO_CLI = arduino-cli -b Arduino-LUFA:avr:leonardo

TARGETS = $(addsuffix .hex, $(addprefix $(TARGET_DIR)/, $(TARGET_NAMES)))

GCC_PATH := $(shell $(ARDUINO_CLI) compile $(PRJ_DIR) --show-properties | grep runtime.tools.avr-gcc.path= | sed "s/.*=//")

all: $(TARGETS) $(TARGET_DIR)/sizes.txt

$(TARGET_DIR)/%.hex: $(SRC) | $(TARGET_DIR) install-core
	@[ "$($*.FLAGS)" ] || ( echo ">> $*.FLAGS is not set"; exit 1 )
	$(ARDUINO_CLI) compile $(PRJ_DIR) --build-property "build.extra_flags={build.usb_flags} -DREFLEX_NO_DEFAULTS $($*.FLAGS)" -e --output-dir $(BUILD_DIR)/$*
	cp $(BUILD_DIR)/$*/ReflexMPG.ino.elf $(TARGET_DIR)/$*.elf
	cp $(BUILD_DIR)/$*/ReflexMPG.ino.hex $(TARGET_DIR)/$*.hex

$(TARGET_DIR)/sizes.txt: $(TARGETS)
	@cd $(TARGET_DIR) && $(GCC_PATH)/bin/avr-size $(notdir $(subst .hex,.elf,$^)) 2>&1 > sizes.txt
	@echo Size Summary 
	@cat $@

$(TARGET_DIR):
	mkdir -p $@

$(TARGET_NAMES): %: $(TARGET_DIR)/%.hex

clean:
	rm -rf $(TARGET_DIR)
	rm -rf $(BUILD_DIR)

.PHONY: all clean install-core $(TARGET_NAMES)
